version: '2'
services:
  kafka:
    image: debezium/kafka:1.7
    ports:
      - 19092:9092
      - 19093:9093
    environment:
      CLUSTER_ID: 5Yr1SIgYQz-b-dgRabWx4g
      BROKER_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093